
repair: all
	g++ -o repair main.o solUno.o MaxHeap.o LinkedList.o iterator.o controller.o

all:
	g++ -c controller/*.cpp
	g++ -c LinkedList/*.cpp
	g++ -c solDos/*.cpp
	g++ -c solUno/*.cpp
	g++ -c main.cpp